### ISSUE TITLE
v0.8.x mac arm64 builds are broken

### ISSUE THREAD

**Issue by quentinhayot** [ItsRiprod/DeskThing#29]
Hi,

None of the v0.8.x arm64 builds will open on my Macbook Pro (M1 chip).
Error: "DeskThing is damaged and can't be opened"

V0.7.0 works fine. It looks there may be an issue with the build config.

**Comment by ItsRiprod** [comment]
HI! I don't know how this slipped through my email unnoticed

To fix this, you just need to do 
```
sudo xattr -r -d com.apple.quarantine DeskThing.app
```
on the installer. There's an unknown issue with the github actions that arent building them *quite* right - but that will hopefully be fixed in a future update.

Also, make sure you have the correct version of the image flashed (fixes an ADB issue for macOS) - I also attached it to this comment. 

If ADB is giving you issue on your desktop, you may also have to do
```
chmod +x /Applications/DeskThing.app/Contents/Resources/mac/adb
```
to allow the native ADB to execute *or* go to Settings and change to Global ADB if you have adb normally installed on your computer

*Click this discord download link to get the proper image to flash to the car thing*
https://cdn.discordapp.com/attachments/1243762430631481395/1272624114766577845/8.4.4_adb_enabled-new.tar.xz?ex=66e33411&is=66e1e291&hm=82e7d7182d53bee82040be86ec9b906d1a169c54ecec0caf8c62cec6dd319e85&

**Comment by ulope** [comment]
> Click this discord download link to get the proper image to flash to the car thing
https://cdn.discordapp.com/attachments/1243762430631481395/1272624114766577845/8.4.4_adb_enabled-new.tar.xz?ex=66e33411&is=66e1e291&hm=82e7d7182d53bee82040be86ec9b906d1a169c54ecec0caf8c62cec6dd319e85&

Seems the link has expired. Shows a message `This content is no longer available.`

**Comment by ItsRiprod** [comment]
@ulope I would recommend going to the discord and using that link located there 

We're trying to get it updated in the MegaNZ file but it hasn't happened yet. 

The discord invite is in https://deskthing.app btw
The download is in #releases in the most recent message
alternatively, you can try using https://cdn.discordapp.com/attachments/1243762430631481395/1272624114766577845/8.4.4_adb_enabled-new.tar.xz?ex=670f5e51&is=670e0cd1&hm=9d02f8082512ae6617018634c66abb9c49eb064a5b85a82c84e8cce3e5cfd5bb&
