### ISSUE TITLE
Case sensitivity issues

### ISSUE THREAD

**Issue by chaseadam** [ItsRiprod/DeskThing#5]
found similar case insensitivity issues to #4  in other places such as server module files

DeskThing/server/apps/spotify > DeskThing/server/apps/Spotify
spotifyHandler.js > SpotifyHandler.js

Similar issues affect all "apps" for the server

**Comment by ItsRiprod** [comment]
Which release is this for?

**Comment by chaseadam** [comment]
per the instructions, it suggested the 0.3.0 release (vs latest). I can switch to using using latest.

**Comment by ItsRiprod** [comment]
Makes since 

I just released v0.5.0 prerelease *today* and haven't gotten to updating all the Readmes and updating the install instructions quite yet 

For today, go ahead and use v0.5.0 as it works far better than v0.3.0

The only issue is that it doesn't support quite as many apps out of the box - but that will change with the full release (probably v0.5.1)

**Comment by ItsRiprod** [comment]
As this has been fixed in v0.5.0+ I think I'm going to mark this as Resolved


For people wanting the command line-ness of v0.3.0, just hand tight - there will be a new version of that which is compatible on things like microcontrollers or PIs so the DeskThing can work practically anywhere

**Comment by chaseadam** [comment]
found two "launchpad" directories in DeskThing/src/views as part of the latest tag, but looks like it was fixed in main

https://github.com/ItsRiprod/DeskThing/tree/v0.5.2-alpha/DeskThing/src/views
